KEYTIMEOUT=1
SHELL_FIRST_EXEC="1"
HISTSIZE=1000
SAVEHIST=$HISTSIZE
HISTDUP=erase
HISTFILE="$HOME/.zsh_history"
export ENV_FILE="$HOME/.environment"
export ZSH_PLUGINS_FOLDER="$RC_FOLDER/plugins"
export TMUX_MOTD="false"
export TMUX_OVERRIDE_TERM="false"
export BAT_THEME="kanagawa"
